### ISSUE TITLE
Create a new Remote Setting collection for the core add-on to use

### ISSUE THREAD

**Issue by rhelmer** [mozilla-rally/rally-core-addon#106]
Currently we are using the same collection that the `about:ion` page in Firefox uses to serve metadata about available study add-ons: https://firefox.settings.services.mozilla.com/v1/buckets/main/collections/pioneer-study-addons-v1/records

Let's create a new one with a better name, and give @Dexterp37 and @hamilton access to make changes and review.

**Comment by rhelmer** [comment]
https://remote-settings.readthedocs.io/en/latest/getting-started.html#create-a-new-official-type-of-remote-settings and https://remote-settings.readthedocs.io/en/latest/tutorial-multi-signoff.html cover the collection and multi-sign-off processes.

**Comment by rhelmer** [comment]
> Let's create a new one with a better name, and give @Dexterp37 and @hamilton access to make changes and review.

Well also @knowtheory and myself :) That should give us good coverage if one or more folks are away.

**Comment by marniepw** [comment]
Related to migration of users.
Since we can update core add-on via RS, do we need this for GTM? @knowtheory is noodling.

**Comment by rhelmer** [comment]
There are two collections we use: `pioneer-study-addons` and `pioneer-content`, the former is metadata about available studies and the latter is for remote delivery of content (issue #167).

I can go ahead and get these collections created, we can decide when/how to use them separately. Updating the records in these collections and adjusting the (optional) schemas is something we can do ourselves, but we need an admin to create the collections.

**Comment by Dexterp37** [comment]
@rhelmer do we need _two_? Do we need to deploy content other than the release notice?

**Comment by rhelmer** [comment]
> 
> 
> @rhelmer do we need _two_? Do we need to deploy content other than the release notice?

We could combine it into one, I don't think we need the `-content` and `-study-addons` suffixes then. Any thoughts on what it should be named? I can go with `rally-core-addon`?

**Comment by Dexterp37** [comment]
> 
> 
> > @rhelmer do we need _two_? Do we need to deploy content other than the release notice?
> 
> We could combine it into one, I don't think we need the `-content` and `-study-addons` suffixes then. Any thoughts on what it should be named? I can go with `rally-core-addon`?

@rhelmer `rally-core-addon` sounds good to me! How would a combined file look?

**Comment by Dexterp37** [comment]
This was done as part of bug https://bugzilla.mozilla.org/show_bug.cgi?id=1691779
