### ISSUE TITLE
support markup in join/leave program/study consent text

### ISSUE THREAD

**Issue by rhelmer** [mozilla-rally/rally-core-addon#112]
The join/leave consent text for studies needs to be displayed before the study is installed. For `about:ion` we settled for using plain text (creating a new `<li>` for each section, delimited by linefeed and setting the [textContent](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent)) but this prohibits doing any kind of rich text, links, etc.

HTML is notoriously difficult to parse while avoiding security issues, and kind of a pain to work with, we should consider serving it as markdown and use a decent markdown parser to turn it into HTML.

**Comment by rhelmer** [comment]
On further discussion we probably need this for the main program join/leave text as well.

**Comment by pdehaan** [comment]
Possibly overkill, but I was doing some random ~~Googling~~ Binging for "MDX for Svelte" and came across https://mdsvex.com/

**Comment by rhelmer** [comment]
Thanks! Looks like this uses https://remark.js.org/ I'll investigate using that for the about:ion implementation. Looks like it supports rehype for trying to sanitize HTML embedded in markdown, but we should consider supporting a more limited subset of markdown. I'll write up a small proposal for this.

**Comment by marniepw** [comment]
May address in the future, but not for alpha.
