### ISSUE TITLE
Support the "Launch Rally" button from the website

### ISSUE THREAD

**Issue by knowtheory** [mozilla-rally/rally-core-addon#140]
Hey this is a mini- or proto- proposal.

One of the primary purposes for our website is going to be calls to action to join Rally.  One of the secondary goals we have for a website down the line is to be able to provide a world accessible URL for individual studies, for a pile of reasons including driving study enrollment/recruitment.

I want to pose the idea that we could coordinate the Core Addon and the Website to solve this problem in a fairly simple way.

If the website has individual pages/urls for studies, I would expect those study pages to have a CTA button for new users to join Rally in order to join a study a user is interested in.

My proposal is that for a CTA button on a study page should have a reliable selector so that the Core Addon can target the button selector.  The Core Addon can then replace the generic "Join Rally" button with a "Join this study" button.

Clicking on this Core Addon controlled button should jump the user into the study listing to the appropriate study card.

Would love feedback on this idea!

**Comment by marniepw** [comment]
Directs user from website directly to the study that a user wants to join.

**Comment by javaun** [comment]
Thanks, I think I understand this one now. I see how this could be GTM. I see how it could also slide to EE. Case where the latter may apply: if we believe that being able to enroll in a new study (i.e. via URL) is a returning user experience, we could kick to post GTM. We will have 2000ish existing users. But the bulk will be net new users coming to the GTM and they will have the ability to get into multiple new studies on first enrollment. (We will have a similar set of timing convos around migration of legacy About Page users to core addon)

**Comment by changecourse** [comment]
We need to hook up the "Get Rally" button (which has detected the core add-on as installed) to serve as a shortcut to launch the add-on in a new tab.

**Comment by tedw** [comment]
This has been added to the website https://github.com/mozilla-rally/site/commit/b442d5d996198636abcb529ce561332e90297ea2

**Comment by Dexterp37** [comment]
![recording](https://user-images.githubusercontent.com/883721/108337588-8ea3bc00-71d5-11eb-96e4-6a1737602213.gif)

Lovely, this seems to work!
