### ISSUE TITLE
"leave rally" copy needs revamping

### ISSUE THREAD

**Issue by hamilton** [mozilla-rally/rally-core-addon#147]

**Comment by changecourse** [comment]
Current mockup/copy:

<img width="668" alt="Overlay" src="https://user-images.githubusercontent.com/6164801/99438722-66a07600-28d1-11eb-92ba-f2b72e0d648c.png">

Thoughts, @javaun @knowtheory ?

**Comment by changecourse** [comment]
Overlay updated in figma, rdy to go.

**Comment by marniepw** [comment]
@changecourse does ready to go mean done done?

**Comment by changecourse** [comment]
Yes, sorry for the vague update. Design and copy approved and currently in development by @hamilton 

![Uploading Screen Shot 2021-01-28 at 4.18.03 PM.png…]()
