### ISSUE TITLE
Study Card Requirements

### ISSUE THREAD

**Issue by marniepw** [mozilla-rally/rally-core-addon#172]
Proposal here (still WIP): https://docs.google.com/document/d/1raIrNddpcSNut6newO0Lcvn7eGn4fpVThWJ__psnlVQ/edit#heading=h.nlpwq3i5fjtq

**Comment by knowtheory** [comment]
@javaun started up a document with study card templates for us to do some light weight mocking to test things out

https://docs.google.com/document/d/1LRNmPU4Jlr3TnjdRjplWGAwgYxiZcL_Rv1BmeRJZ5pw/edit

**Comment by marniepw** [comment]
Need study card copy template to get real data/description to share w/Emily. Assess her concerns. See if info/design needs to be reworked.

Current proposal is SOTU today, not forward looking. Not ready for Emily's review, yet. Are there other studies we can try out in the proposed format, to show her? Not gated on SimSec work. 

Need buckets for study categorization (tags) and data collected. How is this info relayed to the user, clearly?

**Comment by marniepw** [comment]
Will talk to @litkaemily today during our legal sync and get an update on her thoughts. @changecourse would like to put together another design proposal that looks past the Princeton-shaped requirements.

**Comment by knowtheory** [comment]
[Ryan & I have a proposal](https://docs.google.com/document/d/1raIrNddpcSNut6newO0Lcvn7eGn4fpVThWJ__psnlVQ/edit) where we're gathering some of the open questions for driving requirements here.

We will need to have an upcoming conversation about how we're accounting for requirements from both the legal end and from partners & IRB requirements.

**Comment by marniepw** [comment]
Done as per alpha requirements.
