### ISSUE TITLE
Core Add-on present, study installed (side-loaded) but user has not joined Rally: what happens?

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-rally/rally-core-addon#191]
Say we have the following scenario:

1. The Core Add-on is installed but user does not enroll (join rally).
2. User sideload a study.

The partner support library will detect that the core addon is present, but what should we do?

**Comment by hamilton** [comment]
Connects to #191

**Comment by knowtheory** [comment]
Hey!  Here's the product need which we need to confirm:

Regardless of what order a user installs the core addon and a study addon, that study data collection _cannot begin_ until a user consents to the IRB notice (for academic studies).

Background context: we currently have a conversation open about a user's consent UX flow. The question at hand is whether irb notices should live centralized in the Core Addon, or live in individual study addons.  There are a variety of principle and pragmatic driven motivations for either model.  We would like to assess if there are any additional engineering constraints on guaranteeing a user has consented to join a study.

**Comment by marniepw** [comment]
Notes: [https://docs.google.com/document/d/1hFnq-RPP_gWAMbBYzMKywoi9dJ3sIQqGYKo_W6wYdio/edit#heading=h.v5dfboga709r]

**Comment by knowtheory** [comment]
We decided upon putting the consent notices in the core addon.  The Core Addon is the system that captures and records user consent (rather than trusting addons to capture the consent and pass it back up to the core), so the consent dialogs for individual studies need to live in the core addon.

**Comment by knowtheory** [comment]
Additionally we have resolved this ticket.  If a user finds a Rally study on AMO or elsewhere, and they install it, they are taken to the Rally website and prompted to install/open the Rally Core addon.  From there the user can view the list of studies and consent to join the study.
