### ISSUE TITLE
incorporate SimplySecure Privacy Policy redesign into the Core Add-On

### ISSUE THREAD

**Issue by hamilton** [mozilla-rally/rally-core-addon#196]
This is a stub for work that will need to be done to incorporate the outcome of the Privacy Policy design work.

Working doc: https://docs.google.com/document/d/1ndysAp0gtMoQRZ82-fuhhjGKzWIv5r-05aMSr-amtg8/edit?usp=sharing

**Comment by marniepw** [comment]
@changecourse is working with SimSec and Legal on revamped privacy policy.

**Comment by marniepw** [comment]
Related to #108

**Comment by marniepw** [comment]
Split engineering work out from this into separate ticket, and into the backlog.
@changecourse wants Spence to take a stab at illustrations for this.

**Comment by changecourse** [comment]
Legal/content should be finalized by EOW. 

On to illustrations...
