### ISSUE TITLE
Add integration test for un/enrollment flow

### ISSUE THREAD

**Issue by rhelmer** [mozilla-rally/rally-core-addon#227]
We should have a test that runs through the enrollment and unenrollment flow, for both Rally itself as well as studies.

Each test tears down the browser environment, so I suspect we'll end up with a small number of large tests, but we should think about how we might want to break that up a bit.

**Comment by Dexterp37** [comment]
> Each test tears down the browser environment, so I suspect we'll end up with a small number of large tests, but we should think about how we might want to break that up a bit.

We can configure the test runner so that the browser environment is not torn down at the end of each test, but rather only after a _whole test suite_ runs.

**Comment by rhelmer** [comment]
One of the bugs I found is filed in https://github.com/mozilla-ion/ion-core-addon/issues/235

**Comment by marniepw** [comment]
Might be done... @rhelmer to confirm.

**Comment by rhelmer** [comment]
I believe this is fixed in PR #228 we have been able to test the full flow since issue #235 is fixed.
