### ISSUE TITLE
Ensure shortcut arrow has all the right placement & logic

### ISSUE THREAD

**Issue by hamilton** [mozilla-rally/rally-core-addon#232]
This is a stub to ensure we're checking how the shortcut arrow on the "welcome" page of the core add-on actually points to the right spot. Additionally, the shortcut arrow shouldn't appear in all cases.

Sample image:
<img width="1200" alt="add-on_ welcome to Rally" src="https://user-images.githubusercontent.com/6164801/106631530-1765fb00-653a-11eb-9281-60c33b756e23.png">

**Comment by rhelmer** [comment]
@hamilton I spoke to the add-ons folks about this a month or so back, I was told at the time that the toolbar placement is not 100% predictable and WebExtensions cannot introspect the toolbar. I'd be happy to be wrong/misinformed though so I think it's worth looking into further!

**Comment by changecourse** [comment]
@rhelmer @hamilton I feel pretty strongly about our need to make the shortcut more discoverable (once the add-on is installed) so folks know how to get back to Rally, though this is not the only way we could consider doing it. (It's possible that we hold off until we build out a doorhanger to use for prompts/notifications/communication and have that support our 'discoverability' then. 

However, I would love to dig into this a bit more, if you're willing... as far as I can tell, there are a handful of potential issues that would affect knowing exactly where this toolbar item is placed, though I also want to posit that we could potentially adjust/accept some % of risk for misplacement if the vast majority of folks would see it as intended/accurately. 

1. the number of other add-ons someone already has installed could mean that the new add-on icon gets tucked into the overflow toolbar
2. someone's browser window is too small to see newly added add-ons (below 800px?) 
3. the "what's new" icon for new features in a release shifts the add-on toolbar to the left by about 40-50px

From the bullets above, these represent edge cases and minor discrepancies in positioning for a small percentage of users could be acceptable... maybe? 

some potential solutions for each: 
1. if we calculate the position of the farthest right icon (default position for the latest to be installed or the overflow menu) it's technically pointing at the right location either way 
2. we could create a breakpoint for this shortcut element such that it doesn't appear once you get to a small enough browser window
3. I don't have a good solve for this, but do feel that it'll likely happen so infrequently that the offset is acceptable

**Comment by Dexterp37** [comment]
@changecourse @rhelmer what about using [a popup](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Popups), instead? It feels pretty standard, seems to be widely supported.

We could create a nice looking popup snippet.

**Comment by rhelmer** [comment]
> @changecourse @rhelmer what about using [a popup](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Popups), instead? It feels pretty standard, seems to be widely supported.
> 
> We could create a nice looking popup snippet.

AFAIK for unprivileged code, the popup can only be triggered by user interaction (clicking on the icon). We can highlight or otherwise badge the icon but we can't force the pop-up to appear.

We can send [desktop notifications](https://developer.mozilla.org/en-US/docs/Web/API/notification) but that might be too disruptive/distracting since it appears outside of the browser, but it's one of the few ways we can explicitly prompt users.

**Comment by Dexterp37** [comment]
I'll do a quick investigation and let folks know.

**Comment by Dexterp37** [comment]
All right, I checked with @rpl. We might be able to do that using **privileged APIs**, by computing the location of the browser action bar (roughly what @rhelmer suggested earlier). We won't have any way to do that cross-browser.

I'd recommend doing this post launch.

**Comment by changecourse** [comment]
updated image added to description above, per @brizental's suggestion
