### ISSUE TITLE
How are we publishing the core addon and our studies?

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-rally/rally-core-addon#242]
We're now able to build a QA signed version of our core-addon, but we still lack (or at least I lack!) a clear understanding of the following issues:

- How do we get to an officially-signed version of our addon?
- Where can we find the signed XPI?
- How do we download it?
- How do we deliver it?
- How do we track updates?

Our legacy release process had the following section in it:

```markdown
## Publishing the Ion Core Extension

TODO - for now we are publishing the signed XPI as a github release, but in the future it will move to https://addons.mozilla.org
NOTE - if the extension is *not* hosted on addons.mozilla.org, then an alternative update URL must be specified in the `manifest.json` so do this before publishing! https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings#Firefox_Gecko_properties

Upload the signed extension to a github release, and point "Install" button on the static site in `docs/index.html` at the github release. An example of this would be:
https://github.com/mozilla-ion/ion-core-addon/releases/download/2.1/ion_core-2.1.xpi
```

**Comment by rhelmer** [comment]
> Our legacy release process had the following section in it:

Note that this isn't really our [legacy release process](https://docs.google.com/document/d/1nZeRRHJNvbFYREm85yJiZz7b4mKra9DgzDZabyV0cXw/edit), I tried to write this a little forward-looking ;)

Here are some starting points:

> We're now able to build a QA signed version of our core-addon, but we still lack (or at least I lack!) a clear understanding of the following issues:
> 
>     * How do we get to an officially-signed version of our addon?

It's different for core and study add-ons:

- Core uses the privileged release process (PR #243)
- Studies use a standard AMO release process, with "By Mozilla" badging (issue #246)

>     * Where can we find the signed XPI?

Core is privilege-signed on taskcluster but we will upload it to AMO.
Study is signed by AMO without us having to do anything special besides upload it.

>     * How do we download it?

Right now we directly link to the XPI from our [GH docs site](mozilla-ion.github.io/ion-core-addon/) (and soon on our real site when it's ready) but you could also visit the AMO page to install and discover the XPI URL.

>     * How do we deliver it?

Our website is the intended starting point but we can also support users finding it on AMO.

>     * How do we track updates?

I think GitHub releases are the way to go, we should always create a GitHub release and a tag for every add-on release.

We could also look at automation for uploading to AMO via the API, `web-ext` lets you do some of these sort of tasks too.

**Comment by rhelmer** [comment]
The most bespoke and opaque process here IMHO is the privileged signing. Setting aside the initial setup and workflow etc, given a valid extension pushed to mozilla-extensions repo, the following should apply:

https://github.com/mozilla-extensions/xpi-manifest/blob/master/docs/releasing-a-xpi.md#kicking-off-the-release

So you need special VPN and ship-it access, and additionally access to "promote" builds (which sets them up to be signed-off by add-ons review team).

**Comment by Dexterp37** [comment]
Dupe of #65
