### ISSUE TITLE
Does the Core Add-On get synched? Does the same happen to studies?

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-rally/rally-core-addon#277]
I _think_ this is the current behaviour:

- all the addons get synchronized;
- the Rally add-on gets a blank configuration on the other machine (no enrolment);
- studies will pop up a "Get in Rally" page because they will figure the core-addon is there but not installed.

Is this a reasonable behaviour? @hamilton @knowtheory @changecourse ?

@rhelmer I remember you looking into this a while back. Do we have any way to tell an addon to not sync ? (I mean, a _standard_ way that would work in other browsers, too?)

**Comment by hamilton** [comment]
What do you mean by "synchronized" precisely? Can you explain your understanding?

**Comment by Dexterp37** [comment]
> 
> 
> > all the addons get synchronized;
> 
> What do you mean by "synchronized" precisely? Can you explain your understanding?

When using Firefox account (or a Chrome account in Chrome), addons get synchronized (if you choose to do so) on the other machines where that account is used. See for example [this](https://support.mozilla.org/en-US/kb/access-your-add-ons-firefox-accounts).

**Comment by rhelmer** [comment]
> @rhelmer I remember you looking into this a while back. Do we have any way to tell an addon to not sync ? (I mean, a _standard_ way that would work in other browsers, too?)

AFAIK you can tell add-ons not to sync their *data*, but at least (by default) I don't think it's possible to stop syncing of add-ons themselves.

**Comment by changecourse** [comment]
So... do we have a decision to make? 

- Have synchronized devices automatically be enrolled anywhere that the corresponding account is logged in 

- Have the add-ons synced, but have the flag for consent/privacy notice set at the device level to false, and have someone have to go through consent and enrollment for every device (regardless of sync state) 

 Are both of these pathways possible?

**Comment by rhelmer** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1667304

**Comment by rhelmer** [comment]
> So... do we have a decision to make?
> 
>     * Have synchronized devices automatically be enrolled anywhere that the corresponding account is logged in

I'm not sure if we have the ability to tell the difference between a user-triggered and sync-triggered install (from a standard unprivileged webextension)

> 
>     * Have the add-ons synced, but have the flag for consent/privacy notice set at the device level to false, and have someone have to go through consent and enrollment for every device (regardless of sync state)

I think this is what will happen by default, it's the same enrollment flow as when a user installs the study or core add-on directly.

> Are both of these pathways possible?

Yes, although I suspect that we shouldn't auto-enroll on all devices, since we can't make assumptions about how and why users are using sync (they may have one running on a work computer and one on a personal device, etc)

**Comment by changecourse** [comment]
Yes totally agreed.. I wanted to understand what was possible vs what we get for free vs what is appropriate consent overlap... 

I think we're fine with it as is... I'm going to stub in a question to our FAQs around this (assurance would be helpful for folks when understanding how it will work) and perhaps we consider a future enhancement for synced instances and ensuring someone that they'll need to auto-enroll in each device synced... We can likely punt on this until we have an accounts-based plan in the future.

**Comment by Dexterp37** [comment]
> 
> 
> Yes totally agreed.. I wanted to understand what was possible vs what we get for free vs what is appropriate consent overlap...
> 
> I think we're fine with it as is... I'm going to stub in a question to our FAQs around this (assurance would be helpful for folks when understanding how it will work) and perhaps we consider a future enhancement for synced instances and ensuring someone that they'll need to auto-enroll in each device synced... We can likely punt on this until we have an accounts-based plan in the future.

@changecourse thanks. Do you want to stub the FAQ as part of this issue or are you filing a new one? i.e. can we close this one?

**Comment by changecourse** [comment]
Added the question to our FAQ, and adding below for confirmation that I have it worded correctly: 

**Does my involvement in Rally sync via Firefox Accounts?** 

In short, no; we will only enroll you in Rally and it's studies where you explicitly consent to do so.  The add-on itself _will_ sync across desktop instances via Firefox Accounts, but you will have to consent to participate on each instance where your account is synced.

**Comment by Dexterp37** [comment]
> 
> 
> Added the question to our FAQ, and adding below for confirmation that I have it worded correctly:
> 
> **Does my involvement in Rally sync via Firefox Accounts?**
> 
> In short, no; we will only enroll you in Rally and it's studies where you explicitly consent to do so. The add-on itself _will_ sync across desktop instances via Firefox Accounts, but you will have to consent to participate on each instance where your account is synced.
> 
> Once y'all agree with the above Q/A, we can close.

Looks good to me! @rhelmer for confirmation :) ^

**Comment by marniepw** [comment]
@rhelmer confirm described behaviour is as expected.

**Comment by rhelmer** [comment]
lgtm, thanks all!
