### ISSUE TITLE
Remove the legacy "api" abstraction

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-rally/rally-core-addon#287]
The addon currently ships a legacy abstraction that is not really used. In fact, this abstraction adds a layer of complexity that makes debugging problems slightly more difficult.

We should remove [this](https://github.com/mozilla-rally/core-addon/blob/8116ec763e36467af524a065b2c438d84162e271/src/api/firefox.js#L5) and the `web.js` one, directly using the web-extension.js file.

**Comment by Dexterp37** [comment]
A signal of this complexity is the fact that `npm run dev`  currently produces a broken thing :)

**Comment by hamilton** [comment]
Agreed – thanks to Storybook & the component structure, these abstractions are no longer needed.

**Comment by hamilton** [comment]
@Dexterp37 `npm run dev` doesn't currently do anything. Should it, or should we remove it? We have other issues around enabling a dev workflow (#3), so even something like `npm run build; npm run build-addon; web-ext run` wouldn't really meet dev expectations.

**Comment by Dexterp37** [comment]
> 
> 
> @Dexterp37 `npm run dev` doesn't currently do anything. Should it, or should we remove it? We have other issues around enabling a dev workflow (#3), so even something like `npm run build; npm run build-addon; web-ext run` wouldn't really meet dev expectations.

@hamilton you're right :/ It would be ideal to have some command that watches both the "UI" files and the web-extension files, this would make "npm run dev" more useful. I'd be in favour of removing the command right now and reintroduce it once we find a way to watch things that works.

**Comment by rhelmer** [comment]
> > @Dexterp37 `npm run dev` doesn't currently do anything. Should it, or should we remove it? We have other issues around enabling a dev workflow (#3), so even something like `npm run build; npm run build-addon; web-ext run` wouldn't really meet dev expectations.
> 
> @hamilton you're right :/ It would be ideal to have some command that watches both the "UI" files and the web-extension files, this would make "npm run dev" more useful. I'd be in favour of removing the command right now and reintroduce it once we find a way to watch things that works.

Our oldest open issue is about this :) https://github.com/mozilla-rally/core-addon/issues/3

I did some investigation into this at the time but didn't want to block on it, I think it'd be a fine time to revisit as I've been struggling with this too. The workflow right now is not great.

+1 on removing the current command.

**Comment by rhelmer** [comment]
(oops re-reading more carefully issue #3 was already mentioned, I'm 
+1 on just removing the current command and re-adding once we resolve that issue etc)
