### ISSUE TITLE
add support for RemoteSettings via privileged API

### ISSUE THREAD

**Issue by rhelmer** [mozilla-rally/rally-core-addon#296]
Per https://docs.google.com/document/d/1hciaUOnMBRDrVyUaLf0Pjor8Zhtx0_BIoSL5dkMcgMQ we'd like to use the native Firefox `RemoteSettings` API to listen and respond to changes to a remote-settings collection (see issue #106).

This will allow us to update available add-ons from remote, as well as provide a "kill switch" (closes issue #132).

**Comment by rhelmer** [comment]
In terms of API design, I am thinking of adding a listener, something like:

```
firefoxPrivilegedApi.remoteSettings.onMessage((data) => { ... });
```

On extension startup, the `RemoteSettings.on(...)` API will be used to listen for changes to the collection and fire an async callback with the latest data from the collection to all listeners. On extension shutdown, all listeners will be removed and `RemoteSettings.off(...)` will be used to stop listening for updates to the collection.

I don't anticipate we'll ever need more than one listener, but I think this is a better design than having the callback register a separate `RemoteSettings.on` listener for each and every listener.

From the Svelte side, we will update the list of collection in the store whenever the callback fires. Additionally, we will need a way to fetch the latest set of studies on startup:

```
const studies = await firefoxPrivilegedApi.remoteSettings.get();
```

Note that the collection is not passed as a parameter, and is hardcoded in the privileged API class. This is so that we do not have any mistakes, and also so that malicious code cannot get access to data outside of our collection (assuming the malicious code is only on the webextension side of the privilege boundary).

**Comment by rhelmer** [comment]
I think this should cover normal install/uninstall and upgrade states, the only problems I can foresee is if the add-on is removed without uninstall being called (this can happen if the extension is removed directly from the filesystem for instance, which the user or anti-virus/malware).

**Comment by Dexterp37** [comment]
Some feedback on the implementation (in hindsight, this should have probably been a chapter on the proposal!). I believe all of the RS implementation should live within the `core-addon/` part of Rally: Svelte should really know nothing about this.

In fact, all that the UI/Svelte cares about is [this message](https://github.com/mozilla-rally/core-addon/blob/41cd7c8b896dcce5639f64018057d3af0a758b7b/src/api/web-extension.js#L203) being sent by the core whenever the state changes. That status update is generated in few circumstances: when an [addon is installed](https://github.com/mozilla-rally/core-addon/blob/41cd7c8b896dcce5639f64018057d3af0a758b7b/core-addon/Core.js#L135), when the UI [explicitly requests it](https://github.com/mozilla-rally/core-addon/blob/41cd7c8b896dcce5639f64018057d3af0a758b7b/core-addon/Core.js#L184) and [when enrolling in Rally](https://github.com/mozilla-rally/core-addon/blob/41cd7c8b896dcce5639f64018057d3af0a758b7b/core-addon/Core.js#L182).

We already [fetch a remote list](https://github.com/mozilla-rally/core-addon/blob/41cd7c8b896dcce5639f64018057d3af0a758b7b/core-addon/Core.js#L34) (but we embed the JSON file and fetch that for now). Once we have the RemoteSettings machinery in place, I'd expect us to change [_fetchAvailableStudies](https://github.com/mozilla-rally/core-addon/blob/41cd7c8b896dcce5639f64018057d3af0a758b7b/core-addon/Core.js#L34) to get the initial list, and then update `this._availableStudies` whenever a change is detected, updating the UI via `_sendStateUpdateToUI` and acting appropriately on studies if they get enabled/disabled.

@rhelmer  what do you think?

**Comment by rhelmer** [comment]
> Some feedback on the implementation (in hindsight, this should have probably been a chapter on the proposal!). I believe all of the RS implementation should live within the `core-addon/` part of Rally: Svelte should really know nothing about this.
> 
> In fact, all that the UI/Svelte cares about is [this message](https://github.com/mozilla-rally/core-addon/blob/41cd7c8b896dcce5639f64018057d3af0a758b7b/src/api/web-extension.js#L203) being sent by the core whenever the state changes. That status update is generated in few circumstances: when an [addon is installed](https://github.com/mozilla-rally/core-addon/blob/41cd7c8b896dcce5639f64018057d3af0a758b7b/core-addon/Core.js#L135), when the UI [explicitly requests it](https://github.com/mozilla-rally/core-addon/blob/41cd7c8b896dcce5639f64018057d3af0a758b7b/core-addon/Core.js#L184) and [when enrolling in Rally](https://github.com/mozilla-rally/core-addon/blob/41cd7c8b896dcce5639f64018057d3af0a758b7b/core-addon/Core.js#L182).
> 
> We already [fetch a remote list](https://github.com/mozilla-rally/core-addon/blob/41cd7c8b896dcce5639f64018057d3af0a758b7b/core-addon/Core.js#L34) (but we embed the JSON file and fetch that for now). Once we have the RemoteSettings machinery in place, I'd expect us to change [_fetchAvailableStudies](https://github.com/mozilla-rally/core-addon/blob/41cd7c8b896dcce5639f64018057d3af0a758b7b/core-addon/Core.js#L34) to get the initial list, and then update `this._availableStudies` whenever a change is detected, updating the UI via `_sendStateUpdateToUI` and acting appropriately on studies if they get enabled/disabled.
> 
> @rhelmer what do you think?

Yes sorry for glossing over this :) I agree I should not have said "svelte" but rather the background script will do this work and pass messages to the svelte app.

I've been working on this locally and it is quite easy to add a privileged `get` API
 per https://github.com/mozilla-rally/core-addon/issues/296#issuecomment-758880837 that can act as a drop-in replacement for the existing `fetch` in `_fetchAvailableStudies`. We currently don't re-fetch this list so that gets us off the internal `public/locally-available-studies.json` file without any ill effects.

The listener bit (and tests!) is what I am working on now.
