### ISSUE TITLE
configure web-ext to refresh if the Svelte bundle updates

### ISSUE THREAD

**Issue by hamilton** [mozilla-rally/rally-core-addon#3]
From @rhelmer on slack:

> the one thing I feel like we're missing is the ability to have both svelte and the web extension reload seamlessly while running with web-ext... right now you have to npm run build then web-ext run, which we could have a single command for but you don't get the nice Svelte auto-reload

This can probably be surmounted easily.

**Comment by rhelmer** [comment]
One way to do this is to have `rollup -w` running and then watch the build file output with `web-ext run --watch-file public/build/bundle.js`, this seems to work OK.

The way `web-ext` does reload is a little odd in that it's essentially an upgrade not a remove/reinstall of the add-on, so you need to e.g. reload the `moz-extension://` page to see changes if you already have it open, but that's normal `web-ext` behavior so not too surprising I don't think.

**Comment by rhelmer** [comment]
> The way `web-ext` does reload is a little odd in that it's essentially an upgrade not a remove/reinstall of the add-on, so you need to e.g. reload the `moz-extension://` page to see changes if you already have it open, but that's normal `web-ext` behavior so not too surprising I don't think.

Looking into this a bit more, I'm not 100% sure how the "live reload" feature works but I suspect we could get that working as well, which would make the above a little nicer and more like the normal Svelte dev experience.

**Comment by rhelmer** [comment]
> Looking into this a bit more, I'm not 100% sure how the "live reload" feature works but I suspect we could get that working as well, which would make the above a little nicer and more like the normal Svelte dev experience.

Hm, ok so I see that the svelte app inside the webextension is trying to load `<script async="" src="//5db84e64-6e70-184a-9cbd-14f433219489:35729/livereload.js?snipver=1" id="livereloadscript"></script>` but the file isn't present in the extension, I suspect that if we fix this it might Just Work ™

**Comment by hamilton** [comment]
fwiw I think rollup just generates the following w/ communicates w/ the dev server:

```javascript
(function(l, r) { if (l.getElementById('livereloadscript')) return; r = l.createElement('script'); r.async = 1; r.src = '//' + (window.location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1'; r.id = 'livereloadscript'; l.getElementsByTagName('head')[0].appendChild(r) })(window.document);
```

**Comment by hamilton** [comment]
Another option would be to skip the `livereload` from rollup and use [the actual LiveReload](https://github.com/napcs/node-livereload) in some way.

**Comment by rhelmer** [comment]
> > Looking into this a bit more, I'm not 100% sure how the "live reload" feature works but I suspect we could get that working as well, which would make the above a little nicer and more like the normal Svelte dev experience.
> 
> Hm, ok so I see that the svelte app inside the webextension is trying to load `<script async="" src="//5db84e64-6e70-184a-9cbd-14f433219489:35729/livereload.js?snipver=1" id="livereloadscript"></script>` but the file isn't present in the extension, I suspect that if we fix this it might Just Work ™

Oh I just noticed the port `:35729` in there... that's def. not going to work :) Where is that getting set?

**Comment by Dexterp37** [comment]
Potentially relevant: mozilla/web-ext#572
