### ISSUE TITLE
Btn state change when joining a study

### ISSUE THREAD

**Issue by changecourse** [mozilla-rally/rally-core-addon#308]
Since we need add-on installation prompts when electing to join a study (to consent to install) we should change the button state of "Join Study" to disabled, so we can provide additional affordance that something has changed and that the doorhanger is awaiting their next action (to confirm install) 

<img width="1200" alt="add-on_ join a current study (add-on installation prompt)" src="https://user-images.githubusercontent.com/6164801/106637568-1a63ea00-6540-11eb-8cb8-7f5249f38723.png">

**Comment by changecourse** [comment]
@hamilton updated description with proposed approach.

**Comment by marniepw** [comment]
Closed based on current installation flow.
