### ISSUE TITLE
"Sorry to see you go" website routing from "Leave Rally" action

### ISSUE THREAD

**Issue by changecourse** [mozilla-rally/rally-core-addon#309]
When someone chooses to leave Rally, by clicking "Leave Rally" and confirming via an overlay, we should not only perform all installation/leaving actions (already accounted for) but we should also open a "Sorry to see you go" page in our website (URL TBD) 

This issue is to account for performing this final action (opening this page) as part of the leave sequence.

**Comment by hamilton** [comment]
duplicate of #206 – closing that one in favor of this.

**Comment by hamilton** [comment]
@changecourse have we established a URL route for this page? I think that's all we actually will need on the engineering side to implement this.

**Comment by changecourse** [comment]
/leaving-rally is the planned URL, which ThreeSpot will name this
