### ISSUE TITLE
Make `rally.initialize()` reject if the core addon is not there

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-rally/rally-core-addon#321]
We currently have no way in `rally.js` to tell the studies using it that the study should not run (e.g. if the study addon is installed but no core-addon is present/user is not enrolled).

Since studies are **required** to call `rally.initialize`, we should probably make that function reject to inform studies that they should not continue.

Another approach would be to provide another API to notify the study that it can start.

**Comment by Dexterp37** [comment]
@rhelmer thoughts on this?

**Comment by rhelmer** [comment]
> We currently have no way in `rally.js` to tell the studies using it that the study should not run (e.g. if the study addon is installed but no core-addon is present/user is not enrolled).
> 
> Since studies are **required** to call `rally.initialize`, we should probably make that function reject to inform studies that they should not continue.

Rejecting makes sense, I think for issue #132 we probably want to also be able to send messages to studies to have them pause/resume at runtime as well. I suspect that "paused" is going to be basically the same state as "core add-on not present", except that the former wouldn't trigger any sort of onboarding behavior.

> Another approach would be to provide another API to notify the study that it can start.

This is an interesting idea... one thing we should consider is looking at existing actor model patterns for this sort of thing. It might be helpful to think about the core add-on as being in a "supervisor" role, and responsible for managing the lifecycle of the study add-ons, giving out work, handling errors etc.

There's a lot of existing research (most of which I haven't read :)) however I think it would be helpful to at least consider what other people have found useful in decoupled message-passing systems. I think if we do go with this sort of supervisor sort of life-cycle management, then your suggestion of notifying the study fits in. I think it'd be natural too then to provide pause/resume/stop/etc. hooks, so the assumption is that the study add-on state only transitions when it's explicitly told to, and the starting state is always "paused" (run and listen for messages but do nothing else).

The only time a study would take any action on its own is if the core add-on is not present (trigger onboarding).

**Comment by rhelmer** [comment]
Well let me summarize :) 

1. making `rally.initialize()` reject makes sense to me
2. we should think about making `rally.js` own more parts of the study add-on lifecycle beyond data collection

I do like the idea about an API to let the study know when to start, and that's possibly something we could build more on in the future. The implication (in my mind anyway) is that studies would start in an idle state and only transition to "running" once the core add-on sent a message.

**Comment by Dexterp37** [comment]
Thank you for your help!
 
> This is an interesting idea... one thing we should consider is looking at existing actor model patterns for this sort of thing. It might be helpful to think about the core add-on as being in a "supervisor" role, and responsible for managing the lifecycle of the study add-ons, giving out work, handling errors etc.

I like this!

> 
> 
> Well let me summarize :)
> 
>     1. making `rally.initialize()` reject makes sense to me

Awesome, given the short timeframe we could start by doing this.

>     2. we should think about making `rally.js` own more parts of the study add-on lifecycle beyond data collection
>
> I do like the idea about an API to let the study know when to start, and that's possibly something we could build more on in the future. The implication (in my mind anyway) is that studies would start in an idle state and only transition to "running" once the core add-on sent a message.

Yes, I completely agree on this approach. I feel this deserves a proposal on its own :) Let me file another issue for this.
