### ISSUE TITLE
what should happen when a user clicks the "Additional Details" link on the study card?

### ISSUE THREAD

**Issue by hamilton** [mozilla-rally/rally-core-addon#323]
We are likely to make some study card design tweaks before alpha. Even if we don't, we've had a link at the bottom right of the study card that hasn't been wired up to do anything. @changecourse proposed over slack that it could take you to the study detail page of the website. It'd be good for us to understand the partner requirements around this before we can make a decision.

<img width="479" alt="Screen Shot 2021-02-03 at 8 30 21 AM" src="https://user-images.githubusercontent.com/95735/106777774-22806000-65fa-11eb-851c-6f22674583bc.png">

cc @knowtheory

**Comment by changecourse** [comment]
Another option would be for it to take us to the study detail page of the website, but only if there's additional/more context to be had on the website for a given study.

**Comment by knowtheory** [comment]
> Another option would be for it to take us to the study detail page of the website, but only if there's additional/more context to be had on the website for a given study.

Yes, this is my preference, and also, yes!  you are right, that we should make certain there's more content there.

**Comment by changecourse** [comment]
Updated title and description to reflect latest changes in the approach to the study card link.

**Comment by hamilton** [comment]
We agreed that this link will likely go to the Rally study page on the website. Marking this question as "closed"
