### ISSUE TITLE
Make the generated code more stable

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-rally/rally-core-addon#330]
This was reported by the Add-ons team. Fixing this would make reviews a bit simpler. For example, comparing `public/build/bundle.js` between version 0.7.1 and 0.8.0 includes many variable name changes and one letter variables:

![image](https://user-images.githubusercontent.com/883721/106899719-fe09ae00-66f5-11eb-95bd-e6a66d912bb7.png)

**Comment by Dexterp37** [comment]
@hamilton , that's the Svelte generated bundle. Do you have any thoughts on this?

**Comment by hamilton** [comment]
If this aids review, then I'm all for it. I think the savings from minification are more important in other contexts where someone is loading a page and their internet connectivity isn't great. Rally is already probably not a great experience for people with low bandwidth. And at any rate, once someone has the add-on, they already have all the JS they need.

**Comment by Dexterp37** [comment]
> 
> 
> If this aids review, then I'm all for it. I think the savings from whatever minification is making thiis unstable are more important in other contexts where someone is loading a page and their internet connectivity isn't great. Doesn't seem like we're losing too much by changing this.

Yeah, I think it should be ok to drop minification (if that's the problem): before merging the PR we could still check what's the size difference and make the relative considerations.

**Comment by hamilton** [comment]
This will have a substantially small effect on the size vs. all of the image assets I'm about to make a PR for.

**Comment by hamilton** [comment]
Removing `rollup-plugin-terser` grows the bundle size from 142k to to 427k. I'll file a PR that has this integrated.

**Comment by Dexterp37** [comment]
> 
> 
> Removing `rollup-plugin-terser` grows the bundle size from 142k to to 427k. I'll file a PR that has this integrated and you can perhaps decide what you think here. I wish there were a minification package that does not constantly rename, but most of them aren't that sophisticated.

Mh, I indulged in reading the [terser docs](https://github.com/terser/terser#minify-options) a bit. Turns out we can keep the compression on (e.g. remove unused code) and disable the mangling. On my machine this produces a `bundle.js` of 259KB.

@hamilton do you think this would be a reasonable compromise?
