### ISSUE TITLE
Can we distribute studies on AMO without listing them in the search results?

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-rally/rally-core-addon#393]
The [documentation](https://extensionworkshop.com/documentation/publish/firefox-add-on-distribution-agreement/#distribution-certificates-and-review-process) seem to suggest no: `“Unlisted Add-on” means Add-ons that are distributed to End-Users via means other than AMO.`

**Comment by knowtheory** [comment]
I don't think this is a blocker for us, but finding out so that we know the capabilities is important.

My recollection from the conversation i that addons can be flagged as Experimental as well, and reduces discoverability (although it'd also be good to understand how more specifically).

**Comment by Dexterp37** [comment]
@rpl or @muffinresearch, do you know if the above can be achieved?

**Comment by rpl** [comment]
@Dexterp37 unlisted means that they are "not hosted on AMO", they are just checked and signed and so your guess was right (the answer is "no").

The unlisted addons are not going to be visible in the search results, but the developer have to host the signed xpi files on your own.

**Comment by Dexterp37** [comment]
Thank you Luca!
