### ISSUE TITLE
Rename `Rally Core` to `Rally` in the manifest

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-rally/rally-core-addon#397]
See [this slack conversation](https://mozilla.slack.com/archives/C010NL72MT9/p1613175624185800) (the manifest is defined [here](https://github.com/mozilla-rally/rally-core-addon/blob/5faf1f355bf25c92189725725d018b0d7c5a69cb/manifest.json#L5)).

**Comment by rhelmer** [comment]
This requires changing the "name" key in the `manifest.json`. 

Before: 
![image](https://user-images.githubusercontent.com/61412/108103411-c1677c00-703e-11eb-95d3-61473ff73ed3.png)

After:
![image](https://user-images.githubusercontent.com/61412/108103433-c7f5f380-703e-11eb-9fd2-9cf1716d1bff.png)
