### ISSUE TITLE
Stub the`FirefoxPrivilegedApi` module for testing in Chromium-based browsers

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-rally/rally-core-addon#40]
In #38 we slightly refactored the core addon to be clear about what's the privileged API surface. While we don't have a telemetry replacement yet for outside of Firefox, we could still run minimal integration tests on it by mocking that module.

We could do that by creating an empty mock and adding it to the build with Rollup, when targetting Chrome. 

@hamilton @rhelmer thoughts on this and how to do it?

**Comment by hamilton** [comment]
one way to do this would be to use `@rollup/plugin-replace` to swap out which module we're using in the relevant code. I don't want to rely on it too much, but it is a nice way of handling it for integration testing.

**Comment by hamilton** [comment]
This issue is probably pretty stale, since all our web extensions will be on glean.js before long.
