### ISSUE TITLE
ensure Rally deletion pings and other cleanup happen on uninstall

### ISSUE THREAD

**Issue by rhelmer** [mozilla-rally/rally-core-addon#405]
If Rally is uninstalled from within the options page UI, then the `Core._unenroll()` method is called: https://github.com/mozilla-rally/rally-core-addon/blob/d72dd24da2bd41451e4236f59231d32d60625bb7/core-addon/Core.js#L429

However, users can uninstall via `about:addons` or even just context-click on the toolbar icon -> Remove Extension, which will cause the core extension to be removed without the chance to run this sort of unenrollment code.

The one API available to do anything post-uninstall is [browser.runtime.setUninstallURL](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/setUninstallURL), but that only allows registering a URL to open in a new tab, and that's not sufficient for the things we need to do here such as sending deletion pings.

Since the core extension is privileged, we could additionally register an `onUninstall` handler in a privileged API, similar to what we do here with `onShutdown`: https://github.com/mozilla-rally/rally-core-addon/blob/d72dd24da2bd41451e4236f59231d32d60625bb7/core-addon/FirefoxPrivilegedApi.js#L75-L77

**Comment by rhelmer** [comment]
A corner-case that I think we should explicitly avoid trying to handle is where the XPI is deleted from the filesystem while Firefox is shutdown. This isn't a supported way to remove extensions, although we do see it occasionally from malware and anti-virus software. The problem with trying to handle this case is that the code (including any shutdown handler etc) is no longer present on the filesystem, and Firefox will then remove any metadata about the extension on startup.

**Comment by Dexterp37** [comment]
You're right Rob, that's a weird edge case. In addition to the privileged fix, we should think on how this would work cross-browser. The only API we could leverage, as you mentioned, is `setUninstallURL`. That reports this in [the docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/setUninstallURL):

`Sets the URL to be visited when the extension is uninstalled. This may be used to clean up server-side data, do analytics, or implement surveys. The URL can be a maximum 255 characters.`

One potential way to address this would be to add Glean.js to the website too and have the URL opened by `setUninstallURL` to send a deletion-request ping that contains the rally id for the user who is leaving. However, while this seems to be technically feasible, my concern would be sending the rally id over the wire.

We could think more carefully about this edge-case, perhaps encrypting a ping and URL-encoding it in the uninstall URL, then letting the Glean.js in the page send it.

**Comment by rhelmer** [comment]
> You're right Rob, that's a weird edge case. In addition to the privileged fix, we should think on how this would work cross-browser. The only API we could leverage, as you mentioned, is `setUninstallURL`. That reports this in [the docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/setUninstallURL):
> 
> `Sets the URL to be visited when the extension is uninstalled. This may be used to clean up server-side data, do analytics, or implement surveys. The URL can be a maximum 255 characters.`
> 
> One potential way to address this would be to add Glean.js to the website too and have the URL opened by `setUninstallURL` to send a deletion-request ping that contains the rally id for the user who is leaving. However, while this seems to be technically feasible, my concern would be sending the rally id over the wire.
> 
> We could think more carefully about this edge-case, perhaps encrypting a ping and URL-encoding it in the uninstall URL, then letting the Glean.js in the page send it.

Yes, this is definitely worth investigating! I don't think Glean.js in web content would be the right way to handle it though (since it has the sensitive rally ID as you mention).

Couldn't we instead do this reporting on the server side? What I mean is:

1. `setUninstallURL` points to leave page "https://rally.mozilla.org/leaving-rally?[...]"
2. `/leaving-rally` has a server-side handler which takes the query string and reports to us
3. the server-side handler serves an HTML page to the user, equivalent to what we have now

In this case there is nothing run in web content (which could be visible from other extensions or vulnerable to XSS etc.), it would only be in the query string which is part of the HTTPS URL.

This now leaves us still vulnerable to MITM and extensions that can inspect this traffic, but the Rally ID is not part of the JWE-encrypted data so at least the former we're already open to. The latter is a new channel other extensions could inspect unfortunately, but I think it limits our attack surface area.

**Comment by Dexterp37** [comment]
> 
> 
> > You're right Rob, that's a weird edge case. In addition to the privileged fix, we should think on how this would work cross-browser. The only API we could leverage, as you mentioned, is `setUninstallURL`. That reports this in [the docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/setUninstallURL):
> > `Sets the URL to be visited when the extension is uninstalled. This may be used to clean up server-side data, do analytics, or implement surveys. The URL can be a maximum 255 characters.`
> > One potential way to address this would be to add Glean.js to the website too and have the URL opened by `setUninstallURL` to send a deletion-request ping that contains the rally id for the user who is leaving. However, while this seems to be technically feasible, my concern would be sending the rally id over the wire.
> > We could think more carefully about this edge-case, perhaps encrypting a ping and URL-encoding it in the uninstall URL, then letting the Glean.js in the page send it.
> 
> Yes, this is definitely worth investigating! I don't think Glean.js in web content would be the right way to handle it though (since it has the sensitive rally ID as you mention).
> 
> Couldn't we instead do this reporting on the server side? What I mean is:
> 
>     1. `setUninstallURL` points to leave page "[https://rally.mozilla.org/leaving-rally?[...]](https://rally.mozilla.org/leaving-rally?%5B...%5D)"
> 
>     2. `/leaving-rally` has a server-side handler which takes the query string and reports to us
> 
>     3. the server-side handler serves an HTML page to the user, equivalent to what we have now
> 
> 
> In this case there is nothing run in web content (which could be visible from other extensions or vulnerable to XSS etc.), it would only be in the query string which is part of the HTTPS URL.

Ah, neat! I like this solution even better!

> This now leaves us still vulnerable to MITM and extensions that can inspect this traffic, but the Rally ID is not part of the JWE-encrypted data 

It will be when we move to Glean.js.

> so at least the former we're already open to. The latter is a new channel other extensions could inspect unfortunately, but I think it limits our attack surface area.

I agree.

I think this _can_ be a fast follow after launch, but definitely won't make it for Alpha. it's worth flagging it in the engineer meeting.

**Comment by rhelmer** [comment]
Hm OK unfortunately webextension API experiments (that is, privileged code shipped with the add-on and not APIs which are in-Firefox) cannot catch uninstall:

https://firefox-source-docs.mozilla.org/toolkit/components/extensions/webextensions/lifecycle.html#handling-lifecycle-events "Note that these events can be triggered on extensions that are inactive. For that reason, these events can only be handled by extension APIs that are built into the browser. Or, in other words, these events cannot be handled by APIs that are implemented in WebExtension experiments. If the implementation of an API relies on these events for corectness, the API must be built into the browser and not delievered via an experiment."

So I think `setUninstallURL` is the only way we'll be able to handle this, which we know will be the case long-term so I think we have to tackle this now, unfortunately.

I'll open a PR to send along the rally ID from the add-on, I tested and this does work fine. Handling this on the server is a separate issue.

**Comment by rhelmer** [comment]
The only other option I can think of here is that we could ship code in Firefox itself to handle this.

**Comment by marniepw** [comment]
Related to #458

**Comment by marniepw** [comment]
Platform pieces are complete. Shredder pieces are being handled separately, by Anthony.
