### ISSUE TITLE
the "leave study" dialog has inaccurate information about data deletion

### ISSUE THREAD

**Issue by hamilton** [mozilla-rally/rally-core-addon#408]
The second bullet here is inaccurate. We send a deletion ping to remove all of a user's data.

![Screen Shot 2021-02-17 at 10 56 54 AM](https://user-images.githubusercontent.com/95735/108301181-4f825600-7156-11eb-8c16-3ae4f37383de.png)

**Comment by changecourse** [comment]
Update bullet point to: "• Researchers working on this study will no longer     receive data from you, and we will delete any     data that we’ve collected from you to date." 

Design: 
<img width="1200" alt="add-on_ leaving study overlay" src="https://user-images.githubusercontent.com/6164801/108396358-fd801580-71d3-11eb-824f-eb7cd0d88b39.png">

Can I get a 👍 from @javaun or @knowtheory on accuracy of updated statement prior to us moving forward?
