### ISSUE TITLE
Offboard users who delete the Rally addon directly

### ISSUE THREAD

**Issue by knowtheory** [mozilla-rally/rally-core-addon#458]
We provide a mechanism for leaving Rally directly through the Rally experience.

Users, however, have two additional means to remove the Rally addon.  These two mechanisms (addons manager, or right click on addon & click remove) _do not provide a means to offboard users_.

The only option which Rally has, if uninstalled via these other mechanisms, is to open up a web page.

We need to ensure that when users leave, they are _always_ offboarded through a mechanism where we can record their departure, and queue up the request to delete their data.

**Comment by knowtheory** [comment]
[See proposal for further details](https://docs.google.com/document/d/1QKJXTP1t8yRLFJ0BjOL2v_7KIG7cmDi8l5i6IbXbG1k/edit#)

**Comment by Dexterp37** [comment]
Data Engineering work tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1696074

**Comment by knowtheory** [comment]
Checked with Anthony about the completion, deployment & testing (also see the bug above)
