### ISSUE TITLE
Demographic Survey Updates: Income Buckets

### ISSUE THREAD

**Issue by marniepw** [mozilla-rally/rally-core-addon#494]
As a researcher, I need income brackets broken down more granularly, so that I can get finer-grained results for analysis.

- Updating would require updating the core add-on, getting another review, cutting another version, and shipping.

- Alessio: have we validated the request?

- Ted: if we don’t do it, people will have to deal with it and won’t be able to do some types of analyses, or they’ll make a duplicative survey question.

- Can we lock down where we got the survey question from? It comes from the Household Pulse esurvey ([page 16](https://www2.census.gov/data/experimental-data-products/household-pulse-survey/household-pulse-survey-questionnaire.pdf)).  Current [LIVE spread of buckets](https://docs.google.com/document/d/1Zvr52dFH-yNdipG6baGfd_y38TlUMRZ3n5deIdksjmk/edit?ts=5f58375d#).

- Alessio: if we want to make the change, the time for schema / addon change is minimal. Then review. We’re also bound to when the schema is deployed. But we haven’t released yet so we don’t care. A change will take about a week to land.
- Marissa: let’s make sure that what we choose is good for all potential researchers.
- Questions to answer (assigned to marissa):
  - Do we need to make a change? Yes.
  - How urgently do we need to make a change? Unclear.
  - What should this be changed to to accommodate our [future partners](https://mozilla-rally.slack.com/archives/C016S7UV01L/p1615829262002300)?
- Alessio: let’s hold off on this until we have glean.js. We have a potential migration path for us. It’s not worth the risk to change the schema and code change.

**Comment by magorlick** [comment]
Taking notes on potential options [here](https://docs.google.com/document/d/1b2zESmrqhY2uZWMMBArPr-Ux7OKNCj6rqKFz637WJKc/edit#).

Slack thread with partner vote [here](https://mozilla-rally.slack.com/archives/C016S7UV01L/p1615829262002300)

**Comment by magorlick** [comment]
I have evaluated 4 potential Household Income questions and documented the exploration [here](https://docs.google.com/document/d/1kUZpaGpaBHF2vA-YnwqAf30WdOy3VE73jRpY5JB_AfE/edit#heading=h.mdoaoiyvqgfo).

**Recommendation**
I recommend that we change the Household Income question in our core demographic survey to reflect the most granular and standardized Current Population Survey.  Because there are so many response options (41), we should carefully consider the right user experience for the interaction.

@knowtheory , could you review this recommendation for comment / final decision?

**Comment by knowtheory** [comment]
Awesome, thank you for the analysis & recommendation! 

> @knowtheory , could you review this recommendation for comment / final decision?

Yes, let's go for this break down.  Partners have made it clear that they need more granular options for their analyses.  I would like for us to consult with @changecourse prior to us proceeding with implementation.
