### ISSUE TITLE
Implement demographic survey form fields for Income Brackets

### ISSUE THREAD

**Issue by knowtheory** [mozilla-rally/rally-core-addon#496]
See https://github.com/mozilla-rally/rally-core-addon/issues/494 / [this decision brief](https://docs.google.com/document/d/1kUZpaGpaBHF2vA-YnwqAf30WdOy3VE73jRpY5JB_AfE/edit?usp=sharing)

Updated Design replaces the radio buttons to a text field for income entry. 

Figma: https://www.figma.com/file/92ikhj1sHgm3c9jwKp0NHV/Mozilla-Rally-%E2%80%93-Add-on?node-id=2103%3A0 

Expectation is that we'll need to store the specific value entered, but that it may need to be bucketed/categorized to one of the 41 ranges as found in this [brief](https://docs.google.com/document/d/1b2zESmrqhY2uZWMMBArPr-Ux7OKNCj6rqKFz637WJKc/edit#heading=h.6530bmrssqyr)

Additional requirements: 
<img width="804" alt="Screen Shot 2021-03-23 at 10 09 54 AM" src="https://user-images.githubusercontent.com/6164801/112179045-f0ce5300-8bbf-11eb-9b23-32c0244042bc.png">
- Append a "$" and comma(s) (if required) once focus is removed from the field
- Right align the field 
- Require only numeric entry 

Error States: **_potentially none?_** 
- If we're able to restrict the field to just numbers, we do not need an error for other character entry (we should consider this for the zip code field as well)
- There is no specific minimum or maximum for this figure, but we could consider capping (though I don't know that it matters much if someone wishes to put 999999999, for example, as it just will be logged as "over 250k")

**Comment by knowtheory** [comment]
Let's hold off on implementing on this front until we can consult with @changecourse.

**Comment by changecourse** [comment]
Updated description above with designs and additional requirements.
