### ISSUE TITLE
Update Data Schema for Income Brackets

### ISSUE THREAD

**Issue by knowtheory** [mozilla-rally/rally-core-addon#497]
See https://github.com/mozilla-rally/rally-core-addon/issues/494

The schema PR is [here](https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/678).

**Comment by knowtheory** [comment]
Let's hold off on implementing on this front until we can consult with @changecourse.

**Comment by marniepw** [comment]
@rhelmer or @hamilton will pick up this work. Holding off on changing the assignee until then.

**Comment by hamilton** [comment]
@knowtheory @magorlick the schema implementation is blocked on the question of whether we want to send the value as-is or bucketed according to the [CPS income question](https://docs.google.com/document/d/1b2zESmrqhY2uZWMMBArPr-Ux7OKNCj6rqKFz637WJKc/edit#heading=h.9u4e6x8pd2x1) (41 answers).

**Comment by magorlick** [comment]
I don't have a strong preference, the bucketing could happen downstream in a way that lets anyone map the data to an established standard or another currency if we leave it as-is.  However, it might be good for data minimization to to bucket.  The decision we had made when we last spoke about this was to bucket client-side and then send the value.

**Comment by marniepw** [comment]
Decision reached in standup (Hamilton, Marnie, Javaun, Ryan, Alessio, Rob) Tuesday, April 20:

1. UI: we'll release with a blank text field, with client-side validation.
2. Bucketing will happen downstream; researchers can parse income how they see fit.

**Comment by hamilton** [comment]
Schema PR is here: mozilla-services/mozilla-pipeline-schemas#678

Will close this issue once it merges.

**Comment by hamilton** [comment]
Fixed in the above PR. Closing now.
