### ISSUE TITLE
Add more context to Demographic form

### ISSUE THREAD

**Issue by magorlick** [mozilla-rally/rally-core-addon#537]
Add to paragraph at top of demographic form, "Collaborators can join this data to study data to enrich their findings and answer research questions."

**Comment by changecourse** [comment]
This is needed as a blocker for the Princeton study, but not necessarily for our internal release, right @magorlick? Just wanted to confirm for @hamilton

**Comment by magorlick** [comment]
To be clear, this is NOT a blocker for Princeton, this is a nice to have fast-follow. I tried to only tag their requests with alpha-blocker if it blocks them entirely.
