### ISSUE TITLE
study partner logos need to have a max-height, not max-width, in the study card

### ISSUE THREAD

**Issue by hamilton** [mozilla-rally/rally-core-addon#542]
This blocks the Princeton study launch. It's a small style change that is required in the core add-on – we'll need some style rules in place to accommodate different logo shapes. CC @changecourse

**Comment by changecourse** [comment]
Ideally we'd do a square bounding box (60x60) for the study card logo, and try to account for square cropped logos as part of the partner asset gathering process... in instances where a logo is not a 1:1 aspect ratio, we should respect the max height or width of 60px, whichever occurs first, and then center align the other, smaller value, accordingly.

**Comment by magorlick** [comment]
I can add this to our trademark check moving forward.

**Comment by hamilton** [comment]
Just a note that we should check to see if this will be a problem for us for the upcoming launch.

**Comment by hamilton** [comment]
We've decided to tell partners to give us square logos as our solution for now. When we've encountered a situation where we don't have this, we will follow up with the suggestion above.
