### ISSUE TITLE
Port the existing legacy telemetry data collection to Glean.js

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-rally/rally-core-addon#545]
The existing data collection is documented [here](https://github.com/mozilla-rally/rally-core-addon/blob/master/docs/DATA_COLLECTION.md). The pings:

- [x] enrollment (for the platform)
- [x] enrollment (for studies)
- [x] demographics
- [ ] deletion

**Comment by Dexterp37** [comment]
@knowtheory @rhelmer 

Today I verified that we're ingesting data and that this is now ready to be turned on for collection. We will not turn off legacy telemetry collection from the Core Add-on just yet (studies still need to send data and we still need to validate).

However, we should:

- file a bug to create a new environment to send Glean.js collected data to for the Core Add-on.
- turn on Glean collection in the Core Add-on
- release a new version

What do you think, folks? Should we move forward?

**Comment by knowtheory** [comment]
Yes please do move forward!

@Dexterp37 Do you need someone to file for the creation of a new env, or is that something you can tackle?

**Comment by Dexterp37** [comment]
> 
> 
> Yes please do move forward!
> 
> @Dexterp37 Do you need someone to file for the creation of a new env, or is that something you can tackle?

This is done through [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1710406).

**Comment by marniepw** [comment]
@Dexterp37 any updates here? thanks!

**Comment by Dexterp37** [comment]
The deletion part is being handled in [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1698934) by Arkadiusz.

**Comment by jepstein** [comment]
There is a pull request open to fix this

https://github.com/mozilla-rally/rally-core-addon/pull/696

**Comment by jepstein** [comment]
pull request reviewed and merged
