### ISSUE TITLE
the core add-on sends the add-on id in the `schemaNamespace` field when it should send the actual namespace

### ISSUE THREAD

**Issue by hamilton** [mozilla-rally/rally-core-addon#548]
We are not sending the correct `schemaNamespace`, it turns out. The Core add-on is sending this `namespace` field which corresponds to the `studyName` (e.g. `rally-study-01@mozilla.org` for the first Rally study) instead of the actual namespace (e.g. `rally-study-zero-one`).

This will require adding an additional namespace argument in `rally.js` to support this field, probably in the `initialize` method, and then have the `sendPing` method in `rally.js` send that to the Core Add-On [here](https://github.com/mozilla-rally/rally-core-addon/blob/master/support/rally.js#L241-L255) instead of the add-on ID.

One option is to make the API look like the below (e.g. for [`rally-study-01`](https://github.com/mozilla-rally/rally-study-01/blob/master/src/study.js#L24-L32)) – either add a new argument or get rid of the duplicate `keyId` argument and use the `kid` field of the `key`:

```javascript
await rally.initialize(
        "zero-one", // currently the same as the kid field below? is this needed?
        "rally-study-zero-one", // the namespace field we need
        {
          "crv": "P-256",
          "kid": "zero-one",
          "kty": "EC",
          "x": "edhPpqhgK9dD7NaqhQ7Ckw9sU6b39X7XB8HnA366Rjs",
          "y": "GzsfM19n-iH-DVR0iKEoA8BE2CFF46wR__siJ3SdiNs"
        },          
      devMode,
     () => { });
```

cc @Dexterp37 ~ do you have a preference for how we fix this?

**Comment by Dexterp37** [comment]
> One option is to make the API look like the below (e.g. for [`rally-study-01`](https://github.com/mozilla-rally/rally-study-01/blob/master/src/study.js#L24-L32)) – either add a new argument or get rid of the duplicate `keyId` argument and use the `kid` field of the `key`:

Good catch, apologies for not catching this earlier. I agree with you, there's no point in the duplicated key id.  We can get rid of the `keyId`, get rid of [this._keyId](https://github.com/mozilla-rally/rally-core-addon/blob/42b2a3810646557f4363bb6310efb34b06b89dc5/support/rally.js#L54) and use `this.key.kid` whenever that was used. We need to make sure the constructor throws if `kid` is not provided as part of `key`.
