### ISSUE TITLE
Implement Princeton Study Consent in the Core Add On

### ISSUE THREAD

**Issue by magorlick** [mozilla-rally/rally-core-addon#553]
Implements the consent component for the study (run npm run storybook and check the flow story by clicking on the "join study" button)

**Comment by hamilton** [comment]
@magorlick in theory this has been done. You can see a live version [here](https://tender-mcclintock-7d947a.netlify.app/?path=/story/core-add-on-user-flows--main-flow). Click on "join study" under Generic Partner Study to see the IRB. It is currently keyed by Princeton's add-on id `rally.news.study@princeton.edu`.

**Comment by magorlick** [comment]
I compared this to what we have in google drive.  It looks like we elaborated upon the Leaving this Study section and updated the language to reflect the new name.  This was the screen shot that was given to Princeton for the IRB too.  This is done!
