### ISSUE TITLE
SPIKE: Auth in studies & core add-on

### ISSUE THREAD

**Issue by marniepw** [mozilla-rally/rally-core-addon#559]
## Story
 
As the team, we need to understand the technical limitations around an authentication system based on GCP in add-ons, so that we can estimate how much effort it would take to build an identity system.

## Definition of Done 

A prototype web extension that utilizes the [web extension identity API](https://developer.chrome.com/docs/extensions/reference/identity/) along with easy-to-use, built-in GCP & Firebase APIs to auto-authenticate into a study (assume user has authenticated into some Rally interface).

Requirements:
- allow logging in through a Google or custom email + password providers.
- when a study is first installed, it auto-authenticates if the browser has authenticated into their Google account or if I have authenticated into the custom email + password.
- when you open your browser, the previously-installed study should be authenticated already.

The goal is to figure out how much GCP / Firebase meets our needs around these requirements.

## Tasks

_forthcoming_

**Comment by marniepw** [comment]
Flagging to add Mark Reid when he joins our org. @rhelmer , Mark is very interested in your findings here.

**Comment by rhelmer** [comment]
> Flagging to add Mark Reid when he joins our org. @rhelmer , Mark is very interested in your findings here.

Good timing, I just added my notes to https://github.com/rhelmer/chrome-auth-study :) Happy to write this up elsewhere too.

**Comment by marniepw** [comment]
Document tokens and refresh tokens and then this will be complete.
