### ISSUE TITLE
do we need to send individual deletion pings when leaving Rally?

### ISSUE THREAD

**Issue by rhelmer** [mozilla-rally/rally-core-addon#560]
The core add-on currently sends a deletion ping on behalf of each study that was ever activated here: https://github.com/mozilla-rally/rally-core-addon/blob/6a483720435eec1a19efac8ef97288b826b77290/core-addon/Core.js#L516-L527

@Dexterp37 do we really need this now that we send a `deletionId` in the `uninstallURL`?

**Comment by Dexterp37** [comment]
> @Dexterp37 do we really need this now that we send a `deletionId` in the `uninstallURL`?

This is more of a product question than a "data org" need :-) @acmiyaguchi and @knowtheory , do you remember why this choice was made and what was the guarantee we were/are trying to provide?

**Comment by changecourse** [comment]
It may have to do with the promises we make: 

<img width="764" alt="Overlay" src="https://user-images.githubusercontent.com/6164801/116266616-e2cc9e80-a738-11eb-917c-48cc9e170168.png">

**Comment by acmiyaguchi** [comment]
> do we really need this now that we send a deletionId in the uninstallURL?

The uninstallURL is not meant to be the primary mechanism for sending the deletion-request, it's more a hack to catch the clients that fall through the cracks.

**Comment by rhelmer** [comment]
> > do we really need this now that we send a deletionId in the uninstallURL?
> 
> The uninstallURL is not meant to be the primary mechanism for sending the deletion-request, it's more a hack to catch the clients that fall through the cracks.

OK this is the answer I was looking for, thanks :) We can go ahead and continue sending per-study deletion pings when the core add-on is uninstalled, then. I just didn't want to maintain both ways of doing it if it wasn't helpful.
