### ISSUE TITLE
Ensure that the Rally Demographic data retention policy has no end

### ISSUE THREAD

**Issue by magorlick** [mozilla-rally/rally-core-addon#573]
We will always need access to this data set and should ensure that the deletion policy meets this need.

**Comment by Dexterp37** [comment]
> 
> 
> We will always need access to this data set and should ensure that the deletion policy meets this need.

This is interesting: should a different retention policy be applied to this data vs other data?

**Comment by magorlick** [comment]
@Dexterp37 , we need to be very careful that when we promise a data set for partner analysis we aren't deleting it or changing it without telling them. This data set captures one of those promises. We should establish a Rally policy for this kind of data and consider tracking which studies have opted in and on what timeline.  Anthony indicates that we are not automatically deleting this data today.

https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/bad4974cc28a5a3e77cf3aa98b7b096436a8074c/schemas/pioneer-core/demographic-survey/demographic-survey.1.schema.json#L4-L8
