### ISSUE TITLE
Beyond the Paywall: Implement Study Consent and Card in the Core Add On

### ISSUE THREAD

**Issue by magorlick** [mozilla-rally/rally-core-addon#575]
- [x] [Implement Study Card Core Add On](https://github.com/mozilla-rally/rally-core-addon/issues/new/choose) -- this is in the remote settings repo
- [x] [Implement Consent Core Add On](https://github.com/mozilla-rally/rally-core-addon/issues/new/choose)

**Comment by magorlick** [comment]
@hamilton is going to help implement the Consent form.

**Comment by hamilton** [comment]
The consent form is implemented in The above PR. [Here](https://competent-kirch-f0364f.netlify.app/?path=/story/irb-components--stanford-beyond-the-paywall-irb) is a link to the text in storybook form.
