### ISSUE TITLE
fix typo in demographic survey

### ISSUE THREAD

**Issue by hamilton** [mozilla-rally/rally-core-addon#602]
![image (10)](https://user-images.githubusercontent.com/95735/118514057-158b0680-b6e9-11eb-951e-0968a6aa9962.png)

**Comment by dholbert** [comment]
I just fixed this with a drive-by pull request in https://github.com/mozilla-rally/rally-core-addon/pull/626 BTW, so this can probably be closed.

**Comment by hamilton** [comment]
@dholbert thanks!
