### ISSUE TITLE
`rally-core` validation error: required key [app_build] not found

### ISSUE THREAD

**Issue by hamilton** [mozilla-rally/rally-core-addon#641]
Looking through rows of the `rally_core.errors` table, I'm noticing that we get a handful of the following errors every day:

```
org.everit.json.schema.ValidationException: #/client_info: required key [app_build] not found
```

I don't have much context for this error message but we should investigate it.

**Comment by Dexterp37** [comment]
I'm taking over this one, as it's Glean related.
