### ISSUE TITLE
Host the Ion Core add-on on AMO

### ISSUE THREAD

**Issue by rhelmer** [mozilla-rally/rally-core-addon#65]
Our options are:

1. host on AMO. We get auto-updates for free, and users might discover it this way but I think our in-add-on onboarding will work OK for this use case?
2. host ourselves. We need to maintain updates (it's just a JSON file), it makes the core add-on less randomly discoverable which was considered positive for phase 1 but I'm less convinced now.

I think we should go with (1) since this is what we'll have to deal with when we go to the Chrome store anyway, and it's just less hassle.

@hamilton @Dexterp37

**Comment by Dexterp37** [comment]
> 
> 
> Our options are:
> 
>     1. host on AMO. We get auto-updates for free, and users might discover it this way but I think our in-add-on onboarding will work OK for this use case?

I agree with you (1) is preferable here! @changecourse should also have a stake in this decision once the time comes.

**Comment by changecourse** [comment]
+1 to option 1; I'll be sure that the welcome screen and AMO add-on description cross-reference the website so for folks entering through AMO, they can still be primed and educated.

**Comment by rhelmer** [comment]
OK this sgtm - we'll still need to use the privileged signing infrastructure since AMO can only sign "normal" add-ons. I'll make sure we give the add-ons reviewers a heads-up so they don't get worried.

**Comment by rhelmer** [comment]
> I ran this by folks in #addons on slack if it's acceptable to host a privileged Ion Core extension which we later transition to unprivileged (signed with the normal AMO key). I'm going to take this issue and move forward on it if we can. If the say _no_ then I'll close it I guess :)

OK it sounds like it's fine to do this and we can change an AMO hosted add-on from privileged to unprivileged and back so no worries there.

**Comment by Dexterp37** [comment]
> 
> 
> +1 to option 1; I'll be sure that the welcome screen and AMO add-on description cross-reference the website so for folks entering through AMO, they can still be primed and educated.

@changecourse is on board with this idea. @javaun wasn't against this. Both me and @rhelmer agree that AMO hosting is the most convenient option. Let's move forward with this.

**Comment by changecourse** [comment]
Given the concerns laid out in #171, the only thing worth calling out and trying to codify somewhere (@knowtheory in the run book perhaps?) is ensuring that add-on descriptions for each study will need to have a "Requires the Rally core add-on" disclaimer at the start of the study add-on description (with appropriate linking) 

**It makes sense to do this approach (option 1) for now in service to GTM**, _but that we may wish to reconsider post-GTM if we get pushback from AMO (polluting their marketplace with a bunch of child study add-ons) or find that many people are getting lost in the funnel of installing study add-ons without the core add-on installed (#171)_

**Comment by rhelmer** [comment]
We should probably hold off a bit on this until we're ready for users to find it (since we can't hide the AMO page from searches etc), we can self-host in the meantime.

**Comment by hamilton** [comment]
We are going to circle back on this at the beginning of February.

**Comment by rhelmer** [comment]
https://addons.mozilla.org/en-US/firefox/addon/mozilla-rally/
