### ISSUE TITLE
Core add-on update: turn off legacy telemetry for Glean.js studies

### ISSUE THREAD

**Issue by marniepw** [mozilla-rally/rally-core-addon#787]
Related to: https://github.com/mozilla-rally/internal/issues/399

**Comment by marniepw** [comment]
Rob found a bug; fixed and waiting on review from Carla and Mike.

**Comment by rhelmer** [comment]
I've asked for approval from add-ons reviewers in https://mozilla.slack.com/archives/CMKP7NPKN/p1645030442650359
