### ISSUE TITLE
Perform a security review of the Core Addon

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-rally/rally-core-addon#83]
This should be perform for the whole architecture :)

**Comment by marniepw** [comment]
Architecture of the core add on should be the focus. Ensure we haven't missed anything. Builds on top of previous security review work.

**Comment by marniepw** [comment]
Email sent, jclaudius mentioned they're strapped and are onboarding new folks and should have more bandwidth in the new year.

Ted and Javaun to push on.

**Comment by marniepw** [comment]
Emailed Dan on Friday, Dec. 11: 
"Hi Dan!

Hope you're well! Just wanted to circle back around on this and see if there's anything you need from our side? And if not, what the next steps are here? I'm just joining the thread and want to understand how we can best move this forward together.

Thanks!
Marnie"

**Comment by marniepw** [comment]
Scheduled for Thursday, December 17, 30 minutes.

**Comment by marniepw** [comment]
Follow up in January. On the right track, nothing needed/no red flags, though. No explicit approval granted...yet.

**Comment by Dexterp37** [comment]
Here's the [RRA Doc](https://docs.google.com/document/d/1sNw0vyvEeqsvNK0tcLNWUXxG5gLYzi5cDEpjRWXD1Ps/edit#heading=h.ufs6i6416jwo)

**Comment by Dexterp37** [comment]
The security review for the add-on was completed. Here's the [resulting document](https://docs.google.com/document/d/1Enok-8lHLLKwxIfvj5WWxmaegVwCeAON6Z1e3fevc3Q/edit).
